repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace # trims trailing whitespace
    -   id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline
    -   id: check-yaml # checks yaml files for parseable syntax
    -   id: check-added-large-files # checks for files larger than a certain size
    -   id: check-docstring-first # checks a common error of defining a docstring after code
    -   id: check-json # checks json files for parseable syntax
    -   id: check-ast # checks whether the files parse as valid python
    -   id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source
    -   id: requirements-txt-fixer # sorts entries in requirements.txt
    -   id: check-merge-conflict # checks for files that contain merge conflict strings
    -   id: double-quote-string-fixer # replaces double-quoted strings with single-quoted strings
    -   id: detect-private-key # detects the presence of private keys
    -   id: sort-simple-yaml # sorts simple yaml files which consist only of top-level keys
    -   id: check-symlinks # checks for symlinks which do not point to anything
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
    -   id: pycln
        args: [--all]
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: [-l 120]
-   repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
    -   id: yapf
        args: [-vv, -r, "--style={based_on_style: pep8, column_limit: 120}", -i]
        exclude: ^tests/
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: [ "--max-line-length=120", "--extend-ignore=E231,E741,E127,E713" ]
        exclude: ^tests/
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-ll, --skip, "B321,B402,B608", --recursive, .]
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
    -   id: python-safety-dependencies-check
        files: requirements.txt
-   repo: https://github.com/pylint-dev/pylint
    rev: v3.2.2
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
  #          "-sn", # Don't display the score
            "--rcfile=ds-pre-commit-hooks/.pylintrc", # Link to your config file
            "--load-plugins=pylint.extensions.docparams", # Load an extension
            "--ignore-paths=^tests/.*$"
          ]
-   repo: https://github.com/MarcoGorelli/madforhooks # sorts environment.yml
    rev: 0.4.1
    hooks:
    -   id: conda-env-sorter
        exclude: ^tests/
    -   id: no-print-statements
        exclude: ^tests/
-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: dockerfilelint
        stages: [commit]
        exclude: ^tests/
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        exclude: package.lock.json
-   repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        args: ["--fail-under=80", "--verbose", "--ignore-init-method", "--ignore-module", "--ignore-private",
               "--ignore-property-decorators", "--ignore-setters"]
        exclude: ^tests/
-   repo: https://github.com/JanEricNitschke/pymend
    rev: v1.0.10
    hooks:
    -   id: pymend
        name: Pymend
        description: Create, update or convert docstrings in existing Python files, managing several styles.
        entry: pymend
        language: python
        language_version: python3
        types: [text]
        types_or: [python]
        require_serial: true
        args: ["--output-style=numpydoc","--write"]
        exclude: |
            (?x)^(
                tests/|
                (.*)\/(request)_(\w*).py
            )$
-   repo: https://github.com/Carreau/velin
    rev: 0.0.12
    hooks:
    -   id: velin
        args: ["--write"]
        exclude: ^tests/
